### ISSUE TITLE
Split into separate projects

### ISSUE THREAD

**Issue by itssimple** [FuelRats/EliteDangerous-UDP-Dispatcher#1]
## Tasks

- [x] Listener (So you can use a barebone UDP-listener that sends traffic) <kbd>nuget-package</kbd>
  - [x] Command line args to add/remove/configure dispatchers
- [ ] Setup class that should try to automatically find the AppConfig/AppConfigLocal and update it for use with the listener <kbd>nuget-package</kbd>
- [x] Web interface (Visual way to view and configure your listener) <kbd>nuget-package</kbd>
- [ ] Listener as a Service + MSI Installer <kbd>msi-package</kbd>
- [ ] Installation scripts for Linux environments <kbd>bash-scripts</kbd>

### Listener
This is the main part of the tool, that acts as an event dispatcher for multiple tools that also wants to take part of the UDP-stream from Elite: Dangerous

It is configured by adding `IDispatchedEventReceiver` (TCP, UDP, Http Post and Console) to the static `EventReceivers`-list. (It reads from `configuration.json`)

### Setup class
A tool to help setup the connection between Elite: Dangerous and the Listener. 

It should try and find the Elite: Dangerous folder by itself and suggest it to the user, who can then manually change the path, if needed (multiple installations?)

### Web interface
A local web server that gives the user the ability to view the latest entries dispatched, if any exceptions have been encountered, it shall be listed here as well.

The web server should also contain views to configure the dispatchers.

### Listener as a Service
To make it easy for Windows users, we should provide MSI packages for the different parts of this project, and a "full" package that combines all projects.

The MSI-packages should preferably have some configuration steps in them, to select what port should be listened on (or maybe suggest an open one), and also be able to select which Dispatchers to configure from the start

### Linux environment installation scripts
Like many other applications, we should provide an installation-script that should fit most distros.
I.E `wget https://edudp.itssimple.se/install.sh | bash` or something like that.

The script should check for dependencies for running the full software (listener and webserver), and configure the same thing as the `LaaS` (Listener as a Service)
